export const reducerCases = {
  SET_TOKEN: 'SET_TOKEN',
  SET_PLAYLISTS: 'SET_PLAYLISTS',
  SET_USER: 'SET_USER',
  SET_SEARCHALBUMSINFO: 'SET_SEARCHALBUMSINFO',
  SET_SEARCHTRACKSINFO: 'SET_SEARCHTRACKSINFO',
  SET_SEARCHARTISTSINFO: 'SET_SEARCHARTISTSINFO',
  SET_SEARCHINPUTCOMMIT: 'SET_SEARCHINPUTCOMMIT',
};
